/**
 * Trail by id — repo-less share-link resolver.
 *
 * Reads the `trails/_by-id/{id}.json` pointer to find the owning
 * {owner, repo}, then returns the same `{ entry, payload }` shape as the
 * per-repo `/api/trails/{owner}/{repo}/{id}` endpoint plus the resolved
 * owner/repo. This is what the `/trail/{id}` page consumes.
 */

import { NextRequest, NextResponse } from 'next/server';
import { getGitHubToken } from '@/lib/auth/request';
import {
  findIndexEntry,
  getIdPointer,
  getIndex,
  getPayload,
} from '@/lib/trails/s3-storage';
import { validateOwnerRepo } from '@/lib/trails/validation';
import { checkRepoAccess } from '@/lib/trails/github-access';
import { TrailShareError, ShareErrorCodes } from '@/lib/trails/types';
import { getCachedById, type ExperimentalTrailEntry } from '@/lib/pr-trail/cache';
import type { SharedTrailIndexEntry } from '@/lib/trails/types';

/**
 * Synthesize a SharedTrailIndexEntry for an experimental in-memory trail so
 * the by-id envelope shape is identical to the S3-backed path. The entry is
 * derived from the payload itself; the storage-coupled fields
 * (createdBy, githubRepoId) are placeholders — experimental trails have no
 * persisted ownership.
 */
function synthesizeEntry(experimental: ExperimentalTrailEntry): SharedTrailIndexEntry {
  const { payload } = experimental;
  const summaryPreview = (payload.summary ?? '').slice(0, 200);
  const hasDiffSnippets = payload.markers.some(
    (m) => m.snippet?.kind === 'diff',
  );
  return {
    id: payload.id,
    title: payload.title,
    summaryPreview,
    markerCount: payload.markers.length,
    repoNames: payload.repos?.map((r) => r.name).filter(Boolean) ?? [],
    hasDiffSnippets,
    createdAt: payload.createdAt,
    updatedAt: payload.updatedAt,
    sizeBytes: Buffer.byteLength(JSON.stringify(payload), 'utf-8'),
    createdBy: { githubId: 0, githubLogin: 'experimental' },
    githubRepoId: 0,
  };
}

interface Params {
  params: Promise<{ id: string }>;
}

export async function GET(_request: NextRequest, { params }: Params) {
  try {
    const { id } = await params;

    if (!id || typeof id !== 'string') {
      return NextResponse.json(
        { error: 'Invalid trail id', code: ShareErrorCodes.INVALID_REQUEST },
        { status: 400 }
      );
    }

    // Experimental trails (PR-walkthroughs generated by /api/pr-trail) live
    // in process memory only. Resolve those before touching S3 so the share-
    // with-agent CLI command works identically for both. Repo access is still
    // gated — these are synthesized from PR data the user may or may not be
    // entitled to read on a fresh request.
    const experimental = getCachedById(id);
    if (experimental) {
      validateOwnerRepo(experimental.owner, experimental.repo);
      const githubToken = await getGitHubToken();
      const access = await checkRepoAccess(
        experimental.owner,
        experimental.repo,
        githubToken ?? null,
      );
      if (!access) {
        return NextResponse.json(
          {
            error: 'No read access to this repository',
            code: ShareErrorCodes.NO_REPO_ACCESS,
          },
          { status: 403 }
        );
      }
      return NextResponse.json({
        owner: experimental.owner,
        repo: experimental.repo,
        entry: synthesizeEntry(experimental),
        payload: experimental.payload,
      });
    }

    const pointer = await getIdPointer(id);
    if (!pointer) {
      return NextResponse.json(
        { error: 'Trail not found', code: ShareErrorCodes.NOT_FOUND },
        { status: 404 }
      );
    }

    const { owner, repo } = pointer;
    validateOwnerRepo(owner, repo);

    const githubToken = await getGitHubToken();
    const access = await checkRepoAccess(owner, repo, githubToken ?? null);
    if (!access) {
      return NextResponse.json(
        {
          error: 'No read access to this repository',
          code: ShareErrorCodes.NO_REPO_ACCESS,
        },
        { status: 403 }
      );
    }

    const [payload, index] = await Promise.all([
      getPayload(owner, repo, id),
      getIndex(owner, repo),
    ]);

    const entry = findIndexEntry(index, id);

    // Pointer existed but payload/entry doesn't — pointer is stale.
    if (!payload || !entry) {
      return NextResponse.json(
        { error: 'Trail not found', code: ShareErrorCodes.NOT_FOUND },
        { status: 404 }
      );
    }

    return NextResponse.json({ owner, repo, entry, payload });
  } catch (error) {
    if (error instanceof TrailShareError) {
      return NextResponse.json(
        { error: error.message, code: error.code },
        { status: error.statusCode }
      );
    }
    console.error('[Trails] by-id error:', error);
    return NextResponse.json(
      { error: 'Failed to retrieve trail' },
      { status: 500 }
    );
  }
}
