/**
 * Trail by id — repo-less share-link resolver.
 *
 * Reads the `trails/_by-id/{id}.json` pointer to find the owning
 * {owner, repo}, then returns the same `{ entry, payload }` shape as the
 * per-repo `/api/trails/{owner}/{repo}/{id}` endpoint plus the resolved
 * owner/repo. This is what the `/trail/{id}` page consumes.
 */

import { NextRequest, NextResponse } from 'next/server';
import { fetchGitHubUser, getGitHubToken } from '@/lib/auth/request';
import {
  findIndexEntry,
  getIdPointer,
  getIndex,
  getPayload,
} from '@/lib/trails/s3-storage';
import { getAnonNotes } from '@/lib/trails/anon-notes-storage';
import { validateOwnerRepo } from '@/lib/trails/validation';
import { checkRepoAccess, getGitHubDisplayName } from '@/lib/trails/github-access';
import {
  TrailShareError,
  ShareErrorCodes,
  toPublicPayload,
  type StoredTrailPayload,
} from '@/lib/trails/types';
import { getCachedById, type ExperimentalTrailEntry } from '@/lib/pr-trail/cache';
import type { SharedTrailIndexEntry } from '@/lib/trails/types';
import {
  isTrailBookmarked,
  refreshBookmarkedTrailSnapshot,
} from '@/lib/bookmarks/s3-storage';

/**
 * Synthesize a SharedTrailIndexEntry for an experimental in-memory trail so
 * the by-id envelope shape is identical to the S3-backed path. The entry is
 * derived from the payload itself; the storage-coupled fields
 * (createdBy, githubRepoId) are placeholders — experimental trails have no
 * persisted ownership.
 */
function synthesizeEntry(experimental: ExperimentalTrailEntry): SharedTrailIndexEntry {
  const { payload } = experimental;
  const summaryPreview = (payload.summary ?? '').slice(0, 200);
  const hasDiffSnippets = payload.markers.some(
    (m) => m.snippet?.kind === 'diff',
  );
  return {
    id: payload.id,
    title: payload.title,
    summaryPreview,
    markerCount: payload.markers.length,
    repoNames: payload.repos?.map((r) => r.name).filter(Boolean) ?? [],
    hasDiffSnippets,
    createdAt: payload.createdAt,
    updatedAt: payload.updatedAt,
    sizeBytes: Buffer.byteLength(JSON.stringify(payload), 'utf-8'),
    createdBy: { githubId: 0, githubLogin: 'experimental' },
    githubRepoId: 0,
  };
}

interface Params {
  params: Promise<{ id: string }>;
}

export async function GET(_request: NextRequest, { params }: Params) {
  try {
    const { id } = await params;

    if (!id || typeof id !== 'string') {
      return NextResponse.json(
        { error: 'Invalid trail id', code: ShareErrorCodes.INVALID_REQUEST },
        { status: 400 }
      );
    }

    // Experimental trails (PR-walkthroughs generated by /api/pr-trail) live
    // in process memory only. Resolve those before touching S3 so the share-
    // with-agent CLI command works identically for both. Repo access is still
    // gated — these are synthesized from PR data the user may or may not be
    // entitled to read on a fresh request.
    const experimental = getCachedById(id);
    if (experimental) {
      validateOwnerRepo(experimental.owner, experimental.repo);
      const githubToken = await getGitHubToken();
      const access = await checkRepoAccess(
        experimental.owner,
        experimental.repo,
        githubToken ?? null,
      );
      if (!access) {
        return NextResponse.json(
          {
            error: 'No read access to this repository',
            code: ShareErrorCodes.NO_REPO_ACCESS,
          },
          { status: 403 }
        );
      }
      // Experimental trails can't be bookmarked (POST /bookmark requires a real
      // by-id pointer in S3, which they don't have). Hardcode false rather
      // than incur a per-user S3 read for a value that can't be true.
      return NextResponse.json({
        owner: experimental.owner,
        repo: experimental.repo,
        entry: synthesizeEntry(experimental),
        payload: experimental.payload,
        bookmarked: false,
        allowAnonNotes: false,
      });
    }

    const pointer = await getIdPointer(id);
    if (!pointer) {
      return NextResponse.json(
        { error: 'Trail not found', code: ShareErrorCodes.NOT_FOUND },
        { status: 404 }
      );
    }

    const { owner, repo } = pointer;
    validateOwnerRepo(owner, repo);

    const githubToken = await getGitHubToken();
    const access = await checkRepoAccess(owner, repo, githubToken ?? null);
    if (!access) {
      return NextResponse.json(
        {
          error: 'No read access to this repository',
          code: ShareErrorCodes.NO_REPO_ACCESS,
        },
        { status: 403 }
      );
    }

    const [payload, index, anonNotes] = await Promise.all([
      getPayload(owner, repo, id),
      getIndex(owner, repo),
      getAnonNotes(id),
    ]);

    const entry = findIndexEntry(index, id);

    // Pointer existed but payload/entry doesn't — pointer is stale.
    if (!payload || !entry) {
      return NextResponse.json(
        { error: 'Trail not found', code: ShareErrorCodes.NOT_FOUND },
        { status: 404 }
      );
    }

    // `bookmarked` is per-user. Anonymous callers always get false (the by-id
    // route is reachable via public-repo paths without a token). For authed
    // callers with the trail bookmarked, also refresh the snapshot fire-and-
    // forget — the "lazy on item open" half of the snapshot-freshness policy.
    let bookmarked = false;
    if (githubToken) {
      const user = await fetchGitHubUser(githubToken);
      if (user) {
        bookmarked = await isTrailBookmarked(user.id, id);
        if (bookmarked) {
          void refreshBookmarkedTrailSnapshot(user.id, id, entry);
        }
      }
    }

    const stored = payload as StoredTrailPayload;
    const publicPayload = toPublicPayload(stored);
    // Merge anon notes into the panel-facing notes array. They carry
    // an `anon-` id prefix so the trail page can route deletes to
    // the anon-notes endpoint instead of the authored-notes one.
    if (anonNotes.length > 0) {
      publicPayload.notes = [...(publicPayload.notes ?? []), ...anonNotes];
    }
    // The panel's brief renders `From: <author>` from `payload.author`,
    // but CLI/MCP authoring doesn't always set it. Fall back to the
    // creator's GitHub display name (cached 24h via /users/{login});
    // if that isn't set, fall back to the login so the line always
    // shows *something*.
    if (!publicPayload.author && entry.createdBy?.githubLogin) {
      const login = entry.createdBy.githubLogin;
      const displayName = await getGitHubDisplayName(login);
      publicPayload.author = displayName ?? login;
    }

    return NextResponse.json({
      owner,
      repo,
      entry,
      payload: publicPayload,
      bookmarked,
      allowAnonNotes: stored.allowAnonNotes ?? false,
    });
  } catch (error) {
    if (error instanceof TrailShareError) {
      return NextResponse.json(
        { error: error.message, code: error.code },
        { status: error.statusCode }
      );
    }
    console.error('[Trails] by-id error:', error);
    return NextResponse.json(
      { error: 'Failed to retrieve trail' },
      { status: 500 }
    );
  }
}
